application: ceatyp
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /img
  static_dir: static/img

- url: /fonts
  static_dir: static/fonts

- url: /.*
  script: proyecto.app

- url: /_ah/mail/.+
  script: main.app
  login: admin

- url: /_ah/mail/ceatyp@myapp\.appspotmail\.com
  script: main.app
  login: admin

- url: /_ah/bounce
  script: proyecto.app
  login: admin

libraries:
- name: jinja2
  version: latest
  
- name: pycrypto
  version: latest

inbound_services:
- mail
- mail_bounce
